### ISSUE TITLE
GitHub stat

### ISSUE THREAD

**Issue by ghost** [tomondre/tomondre#2]
Is your GitHub live stat is working or not

**Comment by tomondre** [comment]
Do you mean visitor badge? I use it to track number of visitors without displaying it 😄

**Comment by ghost** [comment]
![2023-01-02_16-35](https://user-images.githubusercontent.com/121356786/210223166-9c658d18-e41c-44c9-9997-14115042ec25.png)


Is this Actually works

**Comment by tomondre** [comment]
I believe so, I am using third party tool. 🙂

**Comment by ghost** [comment]
Can you share the tool

**Comment by tomondre** [comment]
https://github.com/anuraghazra/github-readme-stats
